import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {createFixedStageTransaction,createFixedTransportPreflight,STAGE_FILENAMES} from '../../candidates/control-plane/control-plane-root-scripts-stage-mediator-v1.js';
const good={ok:true,preflight_only:true,production_mutation:false,database_mutation:false,deployhq_mutation:false,honartik_mutation:false,imotion_mutation:false,mcp_cutover:false};
async function staged(){const root=fs.mkdtempSync(path.join(os.tmpdir(),'preflight-v1-'));const uid=process.getuid?.()??0,gid=process.getgid?.()??0;await createFixedStageTransaction({stagingRoot:root,ownerUid:uid,ownerGid:gid})();return{root,uid,gid}}
test('uses exact executable and --preflight-only argv after revalidation',async()=>{const{x:unused,...ctx}=await staged();let call;const run=createFixedTransportPreflight({stagingRoot:ctx.root,ownerUid:ctx.uid,ownerGid:ctx.gid,spawn:(exe,args,opt)=>{call={exe,args,opt};return{status:0,stdout:JSON.stringify(good),stderr:''}}});const r=await run();assert.equal(call.exe,'/usr/local/bin/prhm-node');assert.deepEqual(call.args,[path.join(ctx.root,STAGE_FILENAMES.bootstrap),'--preflight-only']);assert.equal(call.opt.shell,false);assert.equal(r.preflight_only,true);assert.equal(r.production_mutation,false);fs.rmSync(ctx.root,{recursive:true,force:true})});
test('unexpected staging-directory entry blocks preflight',async()=>{const ctx=await staged();fs.writeFileSync(path.join(ctx.root,'unexpected.txt'),'x');let called=false;const run=createFixedTransportPreflight({stagingRoot:ctx.root,ownerUid:ctx.uid,ownerGid:ctx.gid,spawn:()=>{called=true;return{status:0,stdout:JSON.stringify(good)}}});await assert.rejects(()=>run(),/staging_root_unexpected_entry/);assert.equal(called,false);fs.rmSync(ctx.root,{recursive:true,force:true})});
test('tampered staged artifact blocks execution',async()=>{const ctx=await staged();fs.appendFileSync(path.join(ctx.root,STAGE_FILENAMES.transport),'x');let called=false;const run=createFixedTransportPreflight({stagingRoot:ctx.root,ownerUid:ctx.uid,ownerGid:ctx.gid,spawn:()=>{called=true;return{status:0,stdout:JSON.stringify(good)}}});await assert.rejects(()=>run(),/staged_file_integrity_mismatch/);assert.equal(called,false);fs.rmSync(ctx.root,{recursive:true,force:true})});
test('wrong mode blocks execution',async()=>{const ctx=await staged();fs.chmodSync(path.join(ctx.root,STAGE_FILENAMES.bootstrap),0o644);let called=false;const run=createFixedTransportPreflight({stagingRoot:ctx.root,ownerUid:ctx.uid,ownerGid:ctx.gid,spawn:()=>{called=true;return{status:0,stdout:JSON.stringify(good)}}});await assert.rejects(()=>run(),/staged_file_mode_mismatch/);assert.equal(called,false);fs.rmSync(ctx.root,{recursive:true,force:true})});
test('contradictory preflight evidence fails closed',async()=>{const ctx=await staged();const run=createFixedTransportPreflight({stagingRoot:ctx.root,ownerUid:ctx.uid,ownerGid:ctx.gid,spawn:()=>({status:0,stdout:JSON.stringify({...good,production_mutation:true}),stderr:''})});await assert.rejects(()=>run(),/preflight_evidence_mismatch/);fs.rmSync(ctx.root,{recursive:true,force:true})});
test('nonzero preflight exit fails closed without returning stdout',async()=>{const ctx=await staged();const run=createFixedTransportPreflight({stagingRoot:ctx.root,ownerUid:ctx.uid,ownerGid:ctx.gid,spawn:()=>({status:7,stdout:'sensitive-output',stderr:'failure'})});await assert.rejects(()=>run(),/preflight_process_failed/);fs.rmSync(ctx.root,{recursive:true,force:true})});
