import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import http from 'node:http';
import {createRootScriptsStageMediator,createFixedStageTransaction,createFixedTransportPreflight,createRootScriptsStageMediatorServer,FIXED_BINDING,ARGUMENTS_SHA256} from '../../candidates/control-plane/control-plane-root-scripts-stage-mediator-v1.js';
const UUID='123e4567-e89b-42d3-a456-426614174000';
const good={ok:true,preflight_only:true,production_mutation:false,database_mutation:false,deployhq_mutation:false,honartik_mutation:false,imotion_mutation:false,mcp_cutover:false};
function call(socketPath,method,url,body){return new Promise((resolve,reject)=>{const b=body===undefined?null:Buffer.from(JSON.stringify(body));const q=http.request({socketPath,method,path:url,headers:b?{'content-type':'application/json','content-length':String(b.length)}:{}},res=>{const a=[];res.on('data',c=>a.push(c));res.on('end',()=>{try{resolve({status:res.statusCode,body:JSON.parse(Buffer.concat(a).toString()||'{}')})}catch(e){reject(e)}})});q.on('error',reject);if(b)q.end(b);else q.end()})}
async function fixture(){
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'mediator-int-')),socket=path.join(dir,'m.sock'),stageRoot=path.join(dir,'stage');let request={request_id:UUID,status:'pending',level:4,action:FIXED_BINDING.action,operation:FIXED_BINDING.operation,project:'control_plane',environment:'production',risk:'critical',arguments_sha256:ARGUMENTS_SHA256,expires_at:'2099-01-01T00:00:00Z'};let consumed=false;
 const mediator=createRootScriptsStageMediator({createApprovalRequest:async()=>({request}),getApprovalRequest:async()=>({request}),decideApprovalRequest:async(id)=>{request={...request,status:'accepted'};return{approval:{execution_authorized:true,action:FIXED_BINDING.action,operation:FIXED_BINDING.operation,arguments_sha256:ARGUMENTS_SHA256,request_id:id},approval_token:'t'.repeat(64)}},approvalBridge:async route=>route==='/v1/validate'?{valid:!consumed}:((consumed=true),{consumed:true})});
 const uid=process.getuid?.()??0,gid=process.getgid?.()??0;
 const stage=createFixedStageTransaction({stagingRoot:stageRoot,ownerUid:uid,ownerGid:gid});
 const preflight=createFixedTransportPreflight({stagingRoot:stageRoot,ownerUid:uid,ownerGid:gid,spawn:()=>({status:0,stdout:JSON.stringify(good),stderr:''})});
 const server=createRootScriptsStageMediatorServer({mediator,stageTransaction:stage,preflight,socketPath:socket});await new Promise((r,j)=>{server.once('error',j);server.listen(socket,r)});return{dir,socket,stageRoot,server};
}
test('end-to-end fixed socket request apply status preflight flow',async()=>{const f=await fixture();try{let r=await call(f.socket,'POST','/v1/request',{});assert.equal(r.status,201);assert.equal(r.body.request_id,UUID);assert.equal(JSON.stringify(r.body).includes('token'),false);r=await call(f.socket,'POST','/v1/apply',{request_id:UUID,second_confirmation:'CONFIRM_LEVEL_4_CRITICAL'});assert.equal(r.status,200);assert.equal(r.body.staged,true);assert.equal(fs.readdirSync(f.stageRoot).length,2);r=await call(f.socket,'GET','/v1/status/'+UUID);assert.equal(r.status,200);assert.equal(r.body.status,'accepted');r=await call(f.socket,'POST','/v1/preflight',{});assert.equal(r.status,200);assert.equal(r.body.preflight_only,true);assert.equal(r.body.production_mutation,false)}finally{await new Promise(r=>f.server.close(r));fs.rmSync(f.dir,{recursive:true,force:true})}});
test('unexpected request/apply fields fail closed',async()=>{const f=await fixture();try{let r=await call(f.socket,'POST','/v1/request',{path:'/tmp/x'});assert.equal(r.status,400);r=await call(f.socket,'POST','/v1/apply',{request_id:UUID,second_confirmation:'CONFIRM_LEVEL_4_CRITICAL',content:'x'});assert.equal(r.status,400)}finally{await new Promise(r=>f.server.close(r));fs.rmSync(f.dir,{recursive:true,force:true})}});
test('router never emits approval token even if a component attempts it',async()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'mediator-leak-')),socket=path.join(dir,'m.sock');const sentinel='SENSITIVE_TOKEN_VALUE_9Q3M7R2X';const mediator={createRequest:async()=>({request_id:UUID,approval_token:sentinel}),getStatus:async()=>({request_id:UUID}),applyApprovedRequest:async()=>({ok:true})};const server=createRootScriptsStageMediatorServer({mediator,stageTransaction:async()=>({ok:true}),preflight:async()=>good,socketPath:socket});await new Promise(r=>server.listen(socket,r));try{const r=await call(socket,'POST','/v1/request',{});assert.equal(r.status,500);assert.equal(JSON.stringify(r.body).includes(sentinel),false);assert.equal(Object.prototype.hasOwnProperty.call(r.body,'approval_token'),false)}finally{await new Promise(r=>server.close(r));fs.rmSync(dir,{recursive:true,force:true})}});
test('source security boundaries remain fixed',()=>{const safe=fs.readFileSync(new URL('../../candidates/agent-mcp/safeFiles-control-plane-root-staging-v1.js',import.meta.url),'utf8');const med=fs.readFileSync(new URL('../../candidates/control-plane/control-plane-root-scripts-stage-mediator-v1.js',import.meta.url),'utf8');const i=safe.indexOf('const ROOT_STAGE_MEDIATOR_SOCKET'),j=safe.indexOf('function proxy',i),slice=safe.slice(i,j);assert.ok(Buffer.byteLength(safe)<=120000);assert.doesNotMatch(slice,/approval_token|authorization|password|api[_-]?key|process\.env/i);assert.doesNotMatch(slice,/systemctl|curl|wget|\/root\//i);const medStatic=med.replace(/const STAGE_ARTIFACTS=Object\.freeze\([\s\S]*?\);\nfunction sha256/,"const STAGE_ARTIFACTS=Object.freeze({});\nfunction sha256");assert.doesNotMatch(medStatic,/systemctl|curl|wget|deployhq\.com|\/home\/honartik|\/mnt\/imotion|node1[^\n]{0,20}recreate/i);assert.doesNotMatch(medStatic,/spawn(?:Sync)?\([^\n]*['"]--apply['"]/);assert.match(medStatic,/--preflight-only/)});
