import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import crypto from 'node:crypto';
import {createFixedStageTransaction,STAGE_FILENAMES} from '../../candidates/control-plane/control-plane-root-scripts-stage-mediator-v1.js';
const sha=b=>crypto.createHash('sha256').update(b).digest('hex');
function sandbox(){const root=fs.mkdtempSync(path.join(os.tmpdir(),'root-stage-v1-'));return{root,tx:createFixedStageTransaction({stagingRoot:root,ownerUid:process.getuid?.()??0,ownerGid:process.getgid?.()??0})}}
test('stages exactly two fixed files with exact hashes and mode 0600',async()=>{const{root,tx}=sandbox();const r=await tx();assert.equal(r.ok,true);assert.deepEqual(fs.readdirSync(root).sort(),Object.values(STAGE_FILENAMES).sort());for(const row of Object.values(r.artifacts)){const b=fs.readFileSync(row.path);assert.equal(b.length,row.bytes);assert.equal(sha(b),row.sha256);assert.equal(fs.statSync(row.path).mode&0o777,0o600)}fs.rmSync(root,{recursive:true,force:true})});
test('rejects symlink staging root',async()=>{const outer=fs.mkdtempSync(path.join(os.tmpdir(),'root-stage-link-'));const real=path.join(outer,'real');fs.mkdirSync(real);const link=path.join(outer,'link');fs.symlinkSync(real,link);const tx=createFixedStageTransaction({stagingRoot:link,ownerUid:process.getuid?.()??0,ownerGid:process.getgid?.()??0});await assert.rejects(()=>tx(),/staging_root_symlink_forbidden/);fs.rmSync(outer,{recursive:true,force:true})});
test('rejects unexpected staging-directory entries before mutation',async()=>{const{root}=sandbox();fs.writeFileSync(path.join(root,'unexpected.txt'),'x');const tx=createFixedStageTransaction({stagingRoot:root,ownerUid:process.getuid?.()??0,ownerGid:process.getgid?.()??0});await assert.rejects(()=>tx(),/staging_root_unexpected_entry/);assert.equal(fs.readFileSync(path.join(root,'unexpected.txt'),'utf8'),'x');fs.rmSync(root,{recursive:true,force:true})});
test('rejects pre-existing destination symlink',async()=>{const{root}=sandbox();const victim=path.join(path.dirname(root),'victim-'+path.basename(root));fs.writeFileSync(victim,'x');fs.symlinkSync(victim,path.join(root,STAGE_FILENAMES.transport));const tx=createFixedStageTransaction({stagingRoot:root,ownerUid:process.getuid?.()??0,ownerGid:process.getgid?.()??0});await assert.rejects(()=>tx(),/destination_not_regular/);fs.rmSync(root,{recursive:true,force:true});fs.rmSync(victim,{force:true})});
test('second-file failure rolls back first file to pre-invocation bytes',async()=>{const{root}=sandbox();const first=path.join(root,STAGE_FILENAMES.transport);fs.writeFileSync(first,'OLD',{mode:0o640});const realRename=fs.renameSync;let finals=0;const fsOps={...fs,renameSync(a,b){if(Object.values(STAGE_FILENAMES).some(n=>b.endsWith('/'+n))){finals++;if(finals===2)throw new Error('forced_second_rename_failure')}return realRename(a,b)}};const tx=createFixedStageTransaction({stagingRoot:root,fsOps,ownerUid:process.getuid?.()??0,ownerGid:process.getgid?.()??0});let err;try{await tx()}catch(e){err=e}assert.ok(err);assert.equal(fs.readFileSync(first,'utf8'),'OLD');assert.equal(err.evidence.rollback_performed,true);assert.equal(err.evidence.rollback_failed,false);fs.rmSync(root,{recursive:true,force:true})});
test('rollback failure is surfaced as critical bounded evidence',async()=>{const{root}=sandbox();const realRename=fs.renameSync;let finals=0;const fsOps={...fs,renameSync(a,b){if(Object.values(STAGE_FILENAMES).some(n=>b.endsWith('/'+n))){finals++;if(finals>=2)throw new Error('forced_rename_failure')}return realRename(a,b)},unlinkSync(){throw new Error('forced_rollback_failure')}};const tx=createFixedStageTransaction({stagingRoot:root,fsOps,ownerUid:process.getuid?.()??0,ownerGid:process.getgid?.()??0});let err;try{await tx()}catch(e){err=e}assert.ok(err);assert.equal(err.evidence.critical_failure,true);assert.equal(err.evidence.rollback_failed,true);fs.rmSync(root,{recursive:true,force:true})});
