const fs=require('fs'),path=require('path'),http=require('http'),crypto=require('crypto');
const SOCKET='/run/prhm-agent-selfmaint/selfmaint.sock';
const ROOT='/home/agent/ssh-agent-runtime/selfmaint-stage';
const MAX_TOTAL=120000,MAX_CHUNK=12000,SHA=/^[a-f0-9]{64}$/,UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const fail=m=>{throw Error(m)},sum=b=>crypto.createHash('sha256').update(b).digest('hex');
function root(){fs.mkdirSync(ROOT,{recursive:true,mode:0o700});try{fs.chmodSync(ROOT,0o700)}catch{}}
function rel(v){if(typeof v!=='string'||!v||v.length>300||v.includes('\0')||v.includes('\\')||path.posix.isAbsolute(v))fail('invalid selfmaint path');const n=path.posix.normalize(v);if(n==='.'||n==='..'||n.startsWith('../'))fail('selfmaint path traversal blocked');if(n.split('/').some(x=>x==='.env'||x==='.ssh'||x==='authorized_keys'||x.startsWith('.env')))fail('sensitive selfmaint path blocked');return n}
function base(s){if(!s||Array.isArray(s)||typeof s!=='object')fail('invalid selfmaint spec');if(!['agent_api','agent_mcp'].includes(s.target))fail('invalid selfmaint target');if(typeof s.expected_sha256!=='string'||!SHA.test(s.expected_sha256))fail('invalid expected_sha256');if(typeof s.reason!=='string'||s.reason.trim().length<3||s.reason.length>1000)fail('invalid reason');return{target:s.target,path:rel(s.path),expected_sha256:s.expected_sha256,reason:s.reason}}
function call(p,m='GET',body){return new Promise((ok,no)=>{const d=body===undefined?null:Buffer.from(JSON.stringify(body)),h=d?{'content-type':'application/json','content-length':d.length}:{};const q=http.request({socketPath:SOCKET,path:p,method:m,headers:h},r=>{let n=0,c=[];r.on('data',x=>{n+=x.length;if(n<=400000)c.push(x)});r.on('end',()=>{if(n>400000)return no(Error('selfmaint_response_too_large'));let o={};try{o=JSON.parse(Buffer.concat(c).toString('utf8')||'{}')}catch{return no(Error('selfmaint_invalid_response'))}if(r.statusCode<200||r.statusCode>=300||o.ok!==true)return no(Error(String(o.error||`selfmaint_rejected_${r.statusCode}`)));ok(o)})});q.setTimeout(90000,()=>q.destroy(Error('selfmaint_timeout')));q.on('error',e=>no(Error('selfmaint_bridge_error:'+e.message)));d?q.end(d):q.end()})}
function pp(id){if(typeof id!=='string'||!UUID.test(id))fail('invalid stage_id');root();return{m:path.join(ROOT,id+'.json'),d:path.join(ROOT,id+'.bin')}}
function save(id,o){const p=pp(id),t=p.m+'.'+process.pid+'.'+Date.now()+'.tmp';fs.writeFileSync(t,JSON.stringify(o)+'\n',{flag:'w',mode:0o600});fs.renameSync(t,p.m)}
function load(id){const p=pp(id);if(!fs.existsSync(p.m)||!fs.existsSync(p.d))fail('stage not found');let s;try{s=JSON.parse(fs.readFileSync(p.m,'utf8'))}catch{fail('invalid stage metadata')}return{...p,s}}
function clean(id){const p=pp(id);for(const f of[p.d,p.m])try{if(fs.existsSync(f))fs.unlinkSync(f)}catch{}}
function chunk(v){if(typeof v!=='string'||!v||v.length>17000||!/^[A-Za-z0-9+/]*={0,2}$/.test(v))fail('invalid base64 chunk');const b=Buffer.from(v,'base64'),a=v.replace(/=+$/,''),z=b.toString('base64').replace(/=+$/,'');if(a!==z)fail('invalid base64 encoding');if(b.length>MAX_CHUNK)fail('chunk too large');return b}
function parse(c){if(typeof c!=='string'||c.length<2||c.length>20000)fail('invalid control-plane command');let s;try{s=JSON.parse(c)}catch{fail('control_plane requires typed JSON')}if(!s||Array.isArray(s)||typeof s!=='object')fail('invalid control-plane spec');return s}
function full(id){const x=load(id),b=fs.readFileSync(x.d);if(b.length!==x.s.total_bytes||x.s.received_bytes!==x.s.total_bytes)fail('stage incomplete');if(sum(b)!==x.s.new_sha256)fail('new sha mismatch');const t=b.toString('utf8');if(!Buffer.from(t,'utf8').equals(b))fail('content must be UTF-8');return{target:x.s.target,path:x.s.path,expected_sha256:x.s.expected_sha256,new_content:t,reason:x.s.reason}}
function createOpsSelfmaintBridge(){return{async execute(command,ctx={}){const s=parse(command),op=s.operation;
if(op==='selfmaint_health')return{...(await call('/health')),operation:op};
if(op==='selfmaint_stage_start'){const b=base(s);if(typeof s.new_sha256!=='string'||!SHA.test(s.new_sha256))fail('invalid new_sha256');if(!Number.isInteger(s.total_bytes)||s.total_bytes<0||s.total_bytes>MAX_TOTAL)fail('invalid total_bytes');const id=crypto.randomUUID(),p=pp(id),st={stage_id:id,...b,new_sha256:s.new_sha256,total_bytes:s.total_bytes,received_bytes:0,created_at:new Date().toISOString(),reason_context:String(ctx.reason||'').slice(0,1000)};fs.writeFileSync(p.d,Buffer.alloc(0),{flag:'wx',mode:0o600});save(id,st);return{ok:true,operation:op,stage_id:id,total_bytes:st.total_bytes,received_bytes:0}}
if(op==='selfmaint_stage_chunk'){const x=load(s.stage_id);if(!Number.isInteger(s.offset)||s.offset!==x.s.received_bytes)fail('stage offset mismatch');const b=chunk(s.content_base64);if(x.s.received_bytes+b.length>x.s.total_bytes)fail('stage exceeds total_bytes');fs.appendFileSync(x.d,b);x.s.received_bytes+=b.length;x.s.updated_at=new Date().toISOString();save(x.s.stage_id,x.s);return{ok:true,operation:op,stage_id:x.s.stage_id,total_bytes:x.s.total_bytes,received_bytes:x.s.received_bytes,complete:x.s.received_bytes===x.s.total_bytes}}
if(op==='selfmaint_stage_status'){const x=load(s.stage_id),n=fs.statSync(x.d).size;return{ok:true,operation:op,stage_id:x.s.stage_id,target:x.s.target,path:x.s.path,total_bytes:x.s.total_bytes,received_bytes:x.s.received_bytes,stored_bytes:n,complete:n===x.s.total_bytes&&x.s.received_bytes===x.s.total_bytes}}
if(op==='selfmaint_request_staged')return{...(await call('/v1/request','POST',full(s.stage_id))),operation:op,stage_id:s.stage_id};
if(op==='selfmaint_confirm'){if(typeof s.request_id!=='string'||!UUID.test(s.request_id))fail('invalid request_id');if(s.second_confirmation!=='CONFIRM_LEVEL_3_PRODUCTION')fail('Level-3 confirmation required');if(s.note!==undefined&&(typeof s.note!=='string'||s.note.length<3||s.note.length>1000))fail('invalid note');return{...(await call('/v1/confirm','POST',{request_id:s.request_id,second_confirmation:s.second_confirmation,...(s.note?{note:s.note}:{})})),operation:op}}
if(op==='selfmaint_apply_staged'){if(typeof s.approval_token!=='string'||s.approval_token.length<32||s.approval_token.length>16384)fail('approval_token required');const out=await call('/v1/apply','POST',{spec:full(s.stage_id),approval_token:s.approval_token});clean(s.stage_id);return{...out,operation:op,stage_id:s.stage_id}}
if(op==='selfmaint_stage_cancel'){load(s.stage_id);clean(s.stage_id);return{ok:true,operation:op,stage_id:s.stage_id,cancelled:true}}
fail('unsupported control-plane operation')}}}
module.exports={createOpsSelfmaintBridge};
