#!/usr/local/bin/prhm-node
'use strict';
const fs=require('node:fs');
const path=require('node:path');
const cp=require('node:child_process');
const STATE_DIR='/var/lib/prhm-company-os-dashboard';
const SNAPSHOT=path.join(STATE_DIR,'snapshot.json');
const PSQL='/usr/bin/psql';
const PASS_FILE='/etc/prhm-p0-db-helper/postgres_superuser_password';
const JOB_DIR='/var/lib/prhm-agent-selfmaint-exec/host-action-v2-jobs';
const REPORTS={
  fail_closed_uat:'/var/lib/prhm-agent-selfmaint-exec/real-market-shadow-uat-v1/latest.json',
  positive_replay_uat:'/var/lib/prhm-agent-selfmaint-exec/real-market-verified-economics-uat-v1/latest.json',
  synthetic_selftest:'/var/lib/prhm-agent-selfmaint-exec/solo-company-selftest-v1/latest.json'
};
const SOURCE_CATALOG=Object.freeze([
  {code:'parscoders',name_fa:'پارس‌کدرز'},
  {code:'karlancer',name_fa:'کارلنسر'},
  {code:'divar',name_fa:'دیوار'}
]);
function fail(m){throw new Error(m)}
function run(file,args,opt={}){const x=cp.spawnSync(file,args,{encoding:'utf8',maxBuffer:4*1024*1024,...opt});if(x.error)fail('exec_error:'+x.error.message);if(x.status!==0)fail('exec_failed:'+String(x.stderr||'').slice(-800));return String(x.stdout||'').trim()}
function query(sql){if(!/^\s*(SELECT|WITH)\b/i.test(sql))fail('query_not_read_only');const pw=fs.readFileSync(PASS_FILE,'utf8').trim();if(!pw)fail('db_password_empty');const env={...process.env,PGPASSWORD:pw,PGOPTIONS:'-c default_transaction_read_only=on -c statement_timeout=12000 -c lock_timeout=1500'};try{return run(PSQL,['-X','-At','-v','ON_ERROR_STOP=1','-h','127.0.0.1','-p','55434','-U','leadops_admin','-d','leadops'],{input:sql,env,timeout:30000})}finally{delete env.PGPASSWORD}}
function jsonOne(sql){const raw=query(sql);if(!raw)return null;return JSON.parse(raw.split(/\r?\n/).find(x=>x.trim().startsWith('{')))}
function jsonRows(sql){const raw=query(sql);if(!raw)return [];return raw.split(/\r?\n/).filter(x=>x.trim().startsWith('{')).map(JSON.parse)}
function sanitize(v){if(Array.isArray(v))return v.map(sanitize);if(!v||typeof v!=='object')return v;const out={};for(const [k,val] of Object.entries(v)){if(/token|secret|private[_-]?key|password|authorization|cookie/i.test(k))continue;out[k]=sanitize(val)}return out}
function readJsonSafe(file){try{return sanitize(JSON.parse(fs.readFileSync(file,'utf8')))}catch{return null}}
function recentJobs(limit=30){try{return fs.readdirSync(JOB_DIR).filter(x=>x.endsWith('.json')).map(name=>{const file=path.join(JOB_DIR,name);return {file,mtime:fs.statSync(file).mtimeMs}}).sort((a,b)=>b.mtime-a.mtime).slice(0,limit).map(x=>{const j=readJsonSafe(x.file)||{};return sanitize({request_id:j.request_id,action:j.action,status:j.status,started_at:j.started_at,finished_at:j.finished_at,updated_at:j.updated_at,approval_id:j.approval_id,approval_consumed:j.approval_consumed,confirmed:j.confirmed,result:j.result?{ok:j.result.ok,decision:j.result.decision,reason:j.result.reason,cleanup_verified:j.result.cleanup_verified,external_id:j.result.external_id,source:j.result.source}:null})})}catch{return []}}
function service(name){const x=cp.spawnSync('/usr/bin/systemctl',['is-active',name],{encoding:'utf8'});return {name,active:x.status===0,state:String(x.stdout||'').trim()||'unknown'}}
function sourceRows(){
  const values=SOURCE_CATALOG.map(x=>`('${x.code}','${x.name_fa}')`).join(',');
  return jsonRows(`WITH wanted(code,name_fa) AS (VALUES ${values}) SELECT json_build_object('code',w.code,'name_fa',w.name_fa,'configured',(s.id IS NOT NULL),'state',CASE WHEN s.id IS NULL THEN 'not_connected' WHEN lower(COALESCE(to_jsonb(s)->>'enabled','true')) IN ('false','0','off','disabled') THEN 'inactive' WHEN COALESCE(NULLIF(to_jsonb(s)->>'last_checked_at',''),NULLIF(to_jsonb(s)->>'last_polled_at',''),NULLIF(to_jsonb(s)->>'last_run_at','')) IS NOT NULL THEN 'active' ELSE 'unknown' END,'last_checked_at',COALESCE(NULLIF(to_jsonb(s)->>'last_checked_at',''),NULLIF(to_jsonb(s)->>'last_polled_at',''),NULLIF(to_jsonb(s)->>'last_run_at','')),'last_activity_at',a.last_activity_at,'discovered_today',COALESCE(a.discovered_today,0),'last_error',COALESCE(NULLIF(to_jsonb(s)->>'last_error',''),NULLIF(to_jsonb(s)->>'error',''))) FROM wanted w LEFT JOIN marketplace.sources s ON s.code=w.code LEFT JOIN LATERAL (SELECT max(o.discovered_at) AS last_activity_at,count(*) FILTER (WHERE o.discovered_at>=date_trunc('day',now())) AS discovered_today FROM marketplace.opportunities o WHERE o.source_id=s.id) a ON true ORDER BY CASE w.code WHEN 'parscoders' THEN 1 WHEN 'karlancer' THEN 2 ELSE 3 END`);
}
function build(){
 const flags=jsonOne(`SELECT json_build_object('P0_SHADOW_MODE',(SELECT enabled FROM automation.p0_feature_flags WHERE flag='P0_SHADOW_MODE'),'P0_DECISION_ENABLED',(SELECT enabled FROM automation.p0_feature_flags WHERE flag='P0_DECISION_ENABLED'),'PROPOSAL_AUTO_SEND_ENABLED',(SELECT enabled FROM automation.p0_feature_flags WHERE flag='PROPOSAL_AUTO_SEND_ENABLED'),'AUTO_PROPOSAL_ENABLED',(SELECT enabled FROM automation.p0_feature_flags WHERE flag='AUTO_PROPOSAL_ENABLED'))`);
 const counters=jsonOne(`SELECT json_build_object('facts',(SELECT count(*) FROM marketplace.economic_input_facts),'decisions',(SELECT count(*) FROM marketplace.opportunity_decisions),'waiting_approval',(SELECT count(*) FROM marketplace.opportunities WHERE status='WAITING_APPROVAL'),'outbox_total',(SELECT count(*) FROM automation.outbox_events),'outbox_published',(SELECT count(*) FROM automation.outbox_events WHERE status='published'),'bids_total',(SELECT count(*) FROM marketplace.bids),'bids_submitted',(SELECT count(*) FROM marketplace.bids WHERE status='SUBMITTED'),'telegram',(SELECT count(*) FROM automation.telegram_messages))`);
 const opportunities=jsonRows(`SELECT json_build_object('id',o.id,'external_id',o.external_id,'source',s.code,'title',o.title,'description',COALESCE(NULLIF(to_jsonb(o)->>'description',''),NULLIF(e.input_snapshot->>'description',''),NULLIF(e.input_snapshot#>>'{raw_payload,description}','')),'status',o.status,'budget_min',o.budget_toman_min,'budget_max',o.budget_toman_max,'discovered_at',o.discovered_at,'expires_at',o.expires_at,'recommendation',e.recommendation,'score',e.total_score,'confidence',e.confidence_score,'service_category',COALESCE(e.input_snapshot->>'service_category',e.input_snapshot#>>'{raw_payload,service_category}'),'economics_count',(SELECT count(*) FROM marketplace.resolved_economic_inputs r WHERE r.opportunity_id=o.id),'original_url',COALESCE(NULLIF(to_jsonb(o)->>'canonical_url',''),NULLIF(to_jsonb(o)->>'source_url',''),NULLIF(e.input_snapshot->>'canonical_url',''),NULLIF(e.input_snapshot->>'source_url',''),NULLIF(e.input_snapshot#>>'{raw_payload,canonical_url}',''),NULLIF(e.input_snapshot#>>'{raw_payload,source_url}','')),'drafts',COALESCE(e.input_snapshot->'upstream_proposal',e.input_snapshot#>'{raw_payload,upstream_proposal}','{}'::jsonb),'communications',COALESCE((SELECT json_agg(json_build_object('kind','bid','channel',s.code,'delivery_status','sent','payload_text',COALESCE(NULLIF(to_jsonb(b)->>'proposal_text',''),NULLIF(to_jsonb(b)->>'message_text',''),NULLIF(to_jsonb(b)->>'message',''),NULLIF(to_jsonb(b)->>'cover_letter',''),NULLIF(to_jsonb(b)->>'text',''),NULLIF(to_jsonb(b)->'payload'->>'proposal',''),NULLIF(to_jsonb(b)->'payload'->>'message',''),NULLIF(to_jsonb(b)->'payload'->>'text','')),'created_at',COALESCE(NULLIF(to_jsonb(b)->>'created_at',''),NULLIF(to_jsonb(b)->>'submitted_at','')),'sent_at',COALESCE(NULLIF(to_jsonb(b)->>'submitted_at',''),NULLIF(to_jsonb(b)->>'sent_at',''),NULLIF(to_jsonb(b)->>'created_at','')),'external_message_id',COALESCE(NULLIF(to_jsonb(b)->>'external_message_id',''),NULLIF(to_jsonb(b)->>'external_bid_id',''),to_jsonb(b)->>'id')) ORDER BY COALESCE(NULLIF(to_jsonb(b)->>'submitted_at',''),NULLIF(to_jsonb(b)->>'created_at','')) DESC) FROM marketplace.bids b WHERE b.opportunity_id=o.id AND upper(COALESCE(to_jsonb(b)->>'status',''))='SUBMITTED'),'[]'::json)) FROM marketplace.opportunities o JOIN marketplace.sources s ON s.id=o.source_id LEFT JOIN LATERAL (SELECT * FROM marketplace.opportunity_evaluations x WHERE x.opportunity_id=o.id ORDER BY x.created_at DESC,x.id DESC LIMIT 1)e ON true WHERE o.status='WAITING_APPROVAL' ORDER BY o.discovered_at DESC LIMIT 25`);
 const decisions=jsonRows(`SELECT json_build_object('opportunity_id',d.opportunity_id,'external_id',o.external_id,'source',s.code,'title',o.title,'decision',d.decision,'reason',d.reason,'economic_floor',d.economic_floor,'final_bid',d.final_bid,'net_profit',d.net_profit,'margin',d.margin,'expected_profit',d.expected_profit,'created_at',d.created_at,'decision_version',d.decision_version) FROM marketplace.opportunity_decisions d JOIN marketplace.opportunities o ON o.id=d.opportunity_id JOIN marketplace.sources s ON s.id=o.source_id ORDER BY d.created_at DESC LIMIT 25`);
 const reports={};for(const [k,f] of Object.entries(REPORTS))reports[k]=readJsonSafe(f);
 const services=['prhm-agent-api.service','prhm-agent-mcp.service','prhm-agent-selfmaint.service','prhm-agent-selfmaint-exec.service','prhm-p0-shadow-worker.service'].map(service);
 const sources=sourceRows();
 const snapshot=sanitize({schema_version:'prhm.company-os-dashboard.snapshot.v2',generated_at:new Date().toISOString(),read_only:true,safety:{p0_live:false,proposal_send:false,bid_send:false,auto_send:false,flags},counters,sources,opportunities,decisions,host_actions:recentJobs(),reports,services});
 fs.mkdirSync(STATE_DIR,{recursive:true,mode:0o750});const tmp=SNAPSHOT+'.'+process.pid+'.tmp';fs.writeFileSync(tmp,JSON.stringify(snapshot,null,2)+'\n',{mode:0o640});fs.chownSync(tmp,0,48);fs.chmodSync(tmp,0o640);fs.renameSync(tmp,SNAPSHOT);return snapshot
}
try{const s=build();process.stdout.write(JSON.stringify({ok:true,snapshot:SNAPSHOT,generated_at:s.generated_at})+'\n')}catch(e){process.stderr.write(String(e&&e.stack||e)+'\n');process.exit(1)}
