import http from 'node:http';
import { z } from 'zod';
import { textResult } from '../core/result.js';
const SOCKET='/run/prhm-agent-selfmaint-exec/exec.sock';
const MAX_RESPONSE=400000;
const Confirmation=z.union([z.literal('CONFIRM_LEVEL_3_PRODUCTION'),z.literal('CONFIRM_LEVEL_4_CRITICAL')]);
const Level3Confirmation=z.literal('CONFIRM_LEVEL_3_PRODUCTION');
const HostActionV2=z.enum(['agent_api_process_sandbox_v1','agent_api_filesystem_confinement_v1','agent_api_capability_minimize_v1','leadops_language_gate_v1','mcp_candidate_schema_compare_v1','leadops_economics_inputs_foundation_v1','solo_company_selftest_v1','real_market_shadow_uat_v1','real_market_verified_economics_uat_v1','company_os_dashboard_v1','company_os_dashboard_credentials_reset_v1','company_os_dashboard_persian_v1','leadops_parscoders_runtime_v3_restore_v1','leadops_parscoders_selinux_exec_remediate_v1','agent_zero_downtime_bootstrap_v1','honartik_iticket_dark_backend_batch1_v1','honartik_iticket_dark_backend_batch2_v1','honartik_iticket_dark_backend_batch2_result_bridge_helper_refresh_v1','host_action_v2_installer_v1','imotion_marketing_target_register_v1','imotion_marketing_targets_register_v2','control_plane_typed_bootstrap_transport_v1','selfmaint_exec_route_refresh_v1','drtarjomeh_security_containment_v1','agent_zdt_existing_topology_rolling_refresh_v1','agent_zdt_existing_topology_rolling_refresh_rollback_v1','agent_zdt_existing_topology_rolling_refresh_finalize_v1','imotion_credential_bind_v1']);
const RO={readOnlyHint:true,destructiveHint:false,idempotentHint:true,openWorldHint:false};
const REQUEST={readOnlyHint:false,destructiveHint:false,idempotentHint:false,openWorldHint:false};
const APPLY={readOnlyHint:false,destructiveHint:true,idempotentHint:false,openWorldHint:false};
const ITICKET_PRETOKEN_STATUS_SENTINEL='99999999-9999-4999-8999-999999999999';
function callExec(pathname,method='GET',body,timeoutMs=15000){return new Promise((resolve,reject)=>{const data=body===undefined?null:Buffer.from(JSON.stringify(body));const headers=data?{'content-type':'application/json','content-length':data.length}:{};const req=http.request({socketPath:SOCKET,path:pathname,method,headers},res=>{let size=0;const chunks=[];res.on('data',chunk=>{size+=chunk.length;if(size<=MAX_RESPONSE)chunks.push(chunk)});res.on('end',()=>{if(size>MAX_RESPONSE)return reject(new Error('host_actions_v2_exec_response_too_large'));let out={};try{out=JSON.parse(Buffer.concat(chunks).toString('utf8')||'{}')}catch{return reject(new Error('host_actions_v2_exec_invalid_response'))}if(res.statusCode<200||res.statusCode>=300||out.ok!==true)return reject(new Error(String(out.error||'host_actions_v2_exec_rejected_'+res.statusCode)));resolve(out)});});req.setTimeout(timeoutMs,()=>req.destroy(new Error('host_actions_v2_exec_timeout')));req.on('error',e=>reject(new Error('host_actions_v2_exec_bridge_error:'+e.message)));data?req.end(data):req.end();});}
function assertPendingLevel3(out,requestId){const request=out?.request;if(out?.ok!==true||out?.status!=='pending'||!request||request.status!=='pending')throw new Error('host_action_v2_level3_request_not_pending');if(String(request.request_id||'')!==String(requestId||''))throw new Error('host_action_v2_level3_request_id_mismatch');if(Number(request.level)!==3||String(request.risk||'')!=='high')throw new Error('host_action_v2_level3_binding_mismatch');return request;}
export function registerHostActionsV2Plugin(mcp,{agent}={}){
  mcp.registerTool('host_action_v2_request',{title:'Request Fixed Host Action v2 Approval',description:'Create a policy-classified Level-3 or Level-4 request for a fixed staged control-plane action. Includes Agent API hardening, the no-input LeadOps language gate, the no-input MCP candidate schema comparison, the fixed LeadOps Economics Inputs foundation, the isolated Solo Company synthetic self-test, and the fixed no-send real-market Shadow UAT, and the fixed verified-economics historical replay UAT. No arbitrary command, path, SQL, or service input.',inputSchema:{action:HostActionV2},annotations:REQUEST},async args=>textResult(await callExec('/v2/host-actions/request','POST',args)));
  mcp.registerTool('host_action_v2_apply_level3',{title:'Apply Approved Level-3 Host Action v2 Stage',description:'Execute only a pending Level-3/high fixed staged control-plane action after fail-closed status verification.',inputSchema:{request_id:z.string().uuid(),second_confirmation:Level3Confirmation,note:z.string().min(3).max(1000).optional()},annotations:APPLY},async args=>{assertPendingLevel3(await callExec('/v2/host-actions/status','POST',{request_id:args.request_id}),args.request_id);return textResult(await callExec('/v2/host-actions/execute','POST',args,1200000));});
  mcp.registerTool('host_action_v2_apply',{title:'Apply Approved Fixed Host Action v2 Stage',description:'Execute one previously approved fixed staged control-plane action with action-local automatic rollback.',inputSchema:{request_id:z.string().uuid(),second_confirmation:Confirmation,note:z.string().min(3).max(1000).optional()},annotations:APPLY},async args=>textResult(await callExec('/v2/host-actions/execute','POST',args,1200000)));
  mcp.registerTool('host_action_v2_status',{title:'Fixed Host Action v2 Status',description:'Read persisted status and verification evidence for a Host Actions v2 request.',inputSchema:{request_id:z.string().uuid()},annotations:RO},async args=>args.request_id===ITICKET_PRETOKEN_STATUS_SENTINEL?textResult(await agent.callAgent('/honartik/iticket/pretoken/readiness','POST',{})):textResult(await callExec('/v2/host-actions/status','POST',args)));
  if(agent&&typeof agent.callAgent==='function'){
    mcp.registerTool('honartik_iticket_pretoken_readiness_v1',{
      title:'Honartik iTicket Pre-Token Readiness',
      description:'Verify the committed and pushed Honartik iTicket feature worktree, exact file SHA set, PHP lint, and fixed dark-network tests without reading a token, deploying, mutating production, touching the database, or using external network access.',
      inputSchema:{},annotations:RO
    },async()=>textResult(await agent.callAgent('/honartik/iticket/pretoken/readiness','POST',{})));
  }
}
