'use strict';
const fs=require('fs'),path=require('path'),crypto=require('crypto'),cp=require('child_process');
const SNAP_ROOT='/var/backups/prhm-central',RUNNER='/usr/local/sbin/prhm-production-central-offsite-backup',SERVICE_FILE='/etc/systemd/system/prhm-production-central-offsite-backup.service',TIMER_FILE='/etc/systemd/system/prhm-production-central-offsite-backup.timer',SERVICE='prhm-production-central-offsite-backup.service',TIMER='prhm-production-central-offsite-backup.timer',STATE='/var/lib/prhm-central-gdrive-bundle/latest.json',POLICY='2026-08-25.1-backup-assurance-central-offsite-v1',CONFIRM='CONFIRM_LEVEL_4_CRITICAL';
const SNAP=/^[0-9]{8}T[0-9]{6}Z$/,SHA=/^[a-f0-9]{64}$/;
const sh=f=>crypto.createHash('sha256').update(fs.readFileSync(f)).digest('hex');function canonical(v){if(v===null||typeof v!=='object')return JSON.stringify(v);if(Array.isArray(v))return `[${v.map(canonical).join(',')}]`;return `{${Object.keys(v).sort().map(k=>`${JSON.stringify(k)}:${canonical(v[k])}`).join(',')}}`};const hb=v=>crypto.createHash('sha256').update(canonical(v)).digest('hex');
function sys(a,t=30000){return cp.execFileSync('systemctl',a,{encoding:'utf8',stdio:['ignore','pipe','pipe'],timeout:t}).trim()}
function sysState(a,t=10000){try{return sys(a,t)}catch(e){const out=String(e&&e.stdout||'').trim();if(out)return out;throw e}}
function tstate(){const enabled=sysState(['is-enabled',TIMER],10000),active=sysState(['is-active',TIMER],10000);if(!['enabled','disabled'].includes(enabled)||!['active','inactive'].includes(active))throw Error('central_offsite_timer_state_unexpected');return{enabled,active}}
function snap(){const a=fs.readdirSync(SNAP_ROOT,{withFileTypes:true}).filter(x=>x.isDirectory()&&SNAP.test(x.name)).map(x=>x.name).sort();if(!a.length)throw Error('central_offsite_snapshot_missing');return a.at(-1)}
function manifest(s){const root=path.join(SNAP_ROOT,s),f=path.join(root,'MANIFEST');const r=cp.spawnSync('/usr/bin/sha256sum',['-c','SHA256SUMS'],{cwd:root,encoding:'utf8',timeout:180000,maxBuffer:400000});if(r.status!==0)throw Error('central_offsite_manifest_verify_failed');return sh(f)}
function current(){const s=snap(),t=tstate();return{snapshot:s,manifest_sha256:manifest(s),runner_sha256:sh(RUNNER),service_unit_sha256:sh(SERVICE_FILE),timer_unit_sha256:sh(TIMER_FILE),timer_enabled:t.enabled,timer_active:t.active,policy_version:POLICY}}
function post(b){const x=JSON.parse(fs.readFileSync(STATE,'utf8'));if(x.status!=='pass'||x.snapshot!==b.snapshot||x.runner_sha256!==b.runner_sha256||x.local_encrypted_repository_check_5pct!=='pass'||x.remote_object_exact_size!=='pass'||!SHA.test(String(x.sha256||'')))throw Error('central_offsite_postrun_evidence_mismatch');return x}
function restore(p){if(p.enabled==='enabled')sys(['enable',TIMER]);else sys(['disable',TIMER]);if(p.active==='active')sys(['start',TIMER]);else sys(['stop',TIMER])}
function createCentralOffsiteRoutes(d){const {readBody,json,callBase,ensureDir,atomicJson,readJson,validateUuid,dataRoot}=d,R=path.join(dataRoot,'central-offsite-requests'),J=path.join(dataRoot,'central-offsite-jobs');ensureDir(R,0o700);ensureDir(J,0o700);const rf=id=>path.join(R,validateUuid(id)+'.json'),jf=id=>path.join(J,validateUuid(id)+'.json');const w=(id,x)=>{const f=jf(id),n={...(fs.existsSync(f)?readJson(f):{}),request_id:id,...x,updated_at:new Date().toISOString()};atomicJson(f,n);return n};const load=id=>{const f=rf(id);if(!fs.existsSync(f))throw Error('central_offsite_request_not_found');const r=readJson(f);if(!r.expires_at||Date.now()>=Date.parse(r.expires_at))throw Error('central_offsite_request_expired');return r};
async function run(id,confirmation,note){let confirmed=false,consumed=false,changed=false;try{const r=load(id),now=current();if(hb(now)!==r.binding_sha256)throw Error('central_offsite_live_binding_drift');w(id,{status:'confirming'});const c=await callBase('/v1/central-offsite/confirm','POST',{request_id:id,second_confirmation:confirmation,...(note?{note}:{})}),token=String(c.approval_token||'');if(token.length<32)throw Error('central_offsite_missing_server_side_approval_token');confirmed=true;w(id,{status:'authorizing',approval_id:c?.approval?.approval_id||null});const a=await callBase('/v1/central-offsite/authorize-consume','POST',{approval_token:token,binding:r.binding});if(a.valid!==true||a.consumed!==true)throw Error('central_offsite_authorization_failed');consumed=true;w(id,{status:'applying'});sys(['start',SERVICE],1800000);const ev=post(r.binding),before={enabled:r.binding.timer_enabled,active:r.binding.timer_active},cur=tstate();if(cur.enabled!=='enabled'||cur.active!=='active'){sys(['enable','--now',TIMER]);changed=true}const fin=tstate();if(fin.enabled!=='enabled'||fin.active!=='active')throw Error('central_offsite_timer_enable_failed');w(id,{status:'succeeded',confirmed,approval_consumed:consumed,finished_at:new Date().toISOString(),snapshot_verified:true,repository_check_5pct:ev.local_encrypted_repository_check_5pct,remote_object_exact_size:ev.remote_object_exact_size,timer_prestate:before,timer_final:fin,rollback_performed:false,secret_value_exposed:false});try{fs.unlinkSync(rf(id))}catch{}}catch(e){let rb=false,re=null;try{const r=fs.existsSync(rf(id))?readJson(rf(id)):null;if(r?.binding){const p={enabled:r.binding.timer_enabled,active:r.binding.timer_active},c=tstate();if(changed||c.enabled!==p.enabled||c.active!==p.active){restore(p);rb=true}}}catch(x){re=String(x.message||x).slice(0,1000)}w(id,{status:'failed',confirmed,approval_consumed:consumed,finished_at:new Date().toISOString(),error:String(e.message||e).slice(0,2000),rollback_performed:rb,rollback_error:re,secret_value_exposed:false});if(confirmed||consumed)try{fs.unlinkSync(rf(id))}catch{}}}
return async(req,res)=>{if(req.method==='POST'&&req.url==='/v1/central-offsite/request'){const x=await readBody(req);if(Object.keys(x||{}).length)throw Error('central_offsite_request_zero_input_only');const b=current(),bh=hb(b),o=await callBase('/v1/central-offsite/request','POST',b),id=o?.request?.request_id;validateUuid(id);if(String(o.arguments_sha256||o?.request?.arguments_sha256||'')!==bh)throw Error('central_offsite_approval_hash_mismatch');atomicJson(rf(id),{request_id:id,binding:b,binding_sha256:bh,expires_at:o?.request?.expires_at||null,created_at:new Date().toISOString()});json(res,201,{ok:true,request:o.request,action:'central_offsite_enable_v1',arguments_sha256:bh,binding:b,secret_value_exposed:false});return true}
if(req.method==='POST'&&req.url==='/v1/central-offsite/execute'){const x=await readBody(req),id=validateUuid(x.request_id);if(x.second_confirmation!==CONFIRM)throw Error('Level-4 confirmation required');load(id);if(fs.existsSync(jf(id))){const j=readJson(jf(id));if(['queued','confirming','authorizing','applying','succeeded'].includes(j.status)){json(res,200,{ok:true,accepted:j.status!=='succeeded',job:j});return true}throw Error('central_offsite_request_already_failed_create_new_request')}const q=w(id,{status:'queued',queued_at:new Date().toISOString(),secret_value_exposed:false});json(res,202,{ok:true,accepted:true,job:q});setTimeout(()=>run(id,x.second_confirmation,x.note),250).unref();return true}
if(req.method==='POST'&&req.url==='/v1/central-offsite/status'){const x=await readBody(req),id=validateUuid(x.request_id);if(fs.existsSync(jf(id))){json(res,200,{ok:true,job:readJson(jf(id))});return true}if(fs.existsSync(rf(id))){json(res,200,{ok:true,status:'pending',request:readJson(rf(id))});return true}json(res,404,{ok:false,error:'central_offsite_status_not_found'});return true}return false}}
module.exports={createCentralOffsiteRoutes,current,hb};
